#!/bin/bash

# Generate Random MAC Address
printf '%02x:%02x:%02x:%02x:%02x:%02x\n' $(((($RANDOM % 256) | 2) & 0xfe)) $(($RANDOM % 256)) $(($RANDOM % 256)) $(($RANDOM % 256)) $(($RANDOM % 256)) $(($RANDOM % 256))
