#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import subprocess

data = str(subprocess.check_output(["fping", "google.com", "-C 1", "-q"], stderr=subprocess.STDOUT))
data = data.split(" ")
ping = str(data[2])
ping_post = "curl -i -XPOST \"http://localhost:8086/write?db=uplink\" --data-binary \"ping,link=dfn,host=google.com value=" + ping + "\""
os.system(ping_post)
